# Generated by Django 3.2.15 on 2023-02-19 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20230215_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderelement',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
