# Generated by Django 3.2.15 on 2023-03-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20230304_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличностью'), ('online', 'Электронно')], db_index=True, default='cash', max_length=20, verbose_name='Способ оплаты'),
            preserve_default=False,
        ),
    ]
