# Generated by Django 3.2.15 on 2023-03-11 20:41

from django.db import migrations
from django.conf import settings
import requests

from ..coordinates import fetch_coordinates


def set_coordinates(apps, schema_editor):
    Restaurant = apps.get_model('foodcartapp', 'Restaurant')
    restaurants = Restaurant.objects.all()
    api_key = settings.YANDEX_GEO_APIKEY
    for restaurant in restaurants:
        try:
            restaurant.latitude, restaurant.longitude = fetch_coordinates(
                api_key,
                restaurant.address,
            )
        except requests.exceptions.HTTPError:
            continue
        restaurant.save()


def move_backward(apps, schema_editor):
    Restaurant = apps.get_model('foodcartapp', 'Restaurant')
    Restaurant.objects.all().update(latitude=None, longitude=None)


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20230311_2038'),
    ]

    operations = [
        migrations.RunPython(set_coordinates, move_backward),
    ]
