# Generated by Django 3.2.15 on 2023-03-11 21:06

from django.db import migrations
from django.conf import settings
import requests

from ..coordinates import fetch_coordinates


def set_coordinates(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    orders = Order.objects.all()
    api_key = settings.YANDEX_GEO_APIKEY
    for order in orders:
        try:
            order.latitude, order.longitude = fetch_coordinates(
                api_key,
                order.address,
            )
        except requests.exceptions.HTTPError:
            continue
        order.save()


def move_backward(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    Order.objects.all().update(latitude=None, longitude=None)


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_auto_20230311_2105'),
    ]

    operations = [
        migrations.RunPython(set_coordinates, move_backward),
    ]
