# Generated by Django 3.2.15 on 2023-03-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_rename_restaurant_order_selected_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('NOT_SET', 'Не выбран'), ('cash', 'Наличностью'), ('online', 'Электронно')], db_index=True, default='NOT_SET', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
