# Generated by Django 3.2.15 on 2023-03-20 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderelement',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
