# Generated by Django 3.2.15 on 2023-02-11 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_orderelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderelement',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество'),
        ),
    ]
