# Generated by Django 3.2.15 on 2023-03-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('01_created', 'Необработанный'), ('02_cooking', 'Готовится'), ('03_delivering', 'Доставляется'), ('04_completed', 'Доставлен')], db_index=True, default='created', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
